name: Build
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - { name: "web-api", path: "Server/VoiceAssistant.Server/"}
          - { name: "worker-s2t", path: "Server/VoiceAssistant.Server.SpeechToText/"}
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to gtihub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PUSH_TOKEN }}

      - name: Build Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.service.path }}/Dockerfile
          push: true
          tags: "ghcr.io/speed-fire/voiceassistant-avrora/${{ matrix.service.name }}:latest,ghcr.io/speed-fire/voiceassistant-avrora/${{ matrix.service.name }}:sha-${{ github.sha }}"